### ISSUE TITLE
Testing with Pytest

### ISSUE THREAD

**Issue by dancergraham** [cowirihy/DynSys#5]
Hello,
Would you consider using pytest for the project tests instead of unittest?  It is most peoples preferred testing package and can automatically detect and run any tests, e.g. any function named `test_something`

**Comment by cowirihy** [comment]
This is a good idea - I wasn't aware of the `pytest` library.

I need to add significant number of unittests in the near future to ally the fears of our QA dept. I'll try doing this using `pytest` when I do so.
